packages:
  - "apps/*"
  - "!apps/desktop"
  - "packages/*"
  - "e2e"

catalog:
  "@ag-ui/client": "0.0.57"
  "@ag-ui/core": "0.0.57"
  "typescript": "^5.9.3"

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@prisma/engines"
  - "@swc/core"
  - better-sqlite3
  - esbuild
  - msw
  - prisma
