/** ConfigService 涉及的全部 process.env 变量名，统一定义避免裸字符串散落各处。 */
export const EnvKey = {
  PORT: "PORT",
  CONTEXT: "AGEWORK_CONTEXT",
  SERVER_BASE_URL: "AGEWORK_SERVER_BASE_URL",
  BODY_LIMIT: "AGEWORK_BODY_LIMIT",
  SERVE_FRONTEND: "AGEWORK_SERVE_FRONTEND",
  LOG_LEVEL: "AGEWORK_LOG_LEVEL",
  DATA_DIR: "AGEWORK_DATA_DIR",
  PRIVATE_DATABASE_URL: "AGEWORK_PRIVATE_DATABASE_URL",
  PRIVATE_JWT_SECRET: "AGEWORK_PRIVATE_JWT_SECRET",
  PRIVATE_ADMIN_INIT_KEY: "AGEWORK_PRIVATE_ADMIN_INIT_KEY",
  PRIVATE_OPENSANDBOX_API_KEY: "AGEWORK_PRIVATE_OPENSANDBOX_API_KEY",
  DEV_AUTH_DISABLED: "AGEWORK_DEV_AUTH_DISABLED",
  RUNTIME_ALLOWED_TYPES: "AGEWORK_RUNTIME_ALLOWED_TYPES",
  RUNTIME_ALLOWED_ISOLATION_SCOPES: "AGEWORK_RUNTIME_ALLOWED_ISOLATION_SCOPES",
  SANDBOX_OPENSANDBOX_DOMAIN: "AGEWORK_SANDBOX_OPENSANDBOX_DOMAIN",
  SANDBOX_OPENSANDBOX_PROTOCOL: "AGEWORK_SANDBOX_OPENSANDBOX_PROTOCOL",
  SANDBOX_OPENSANDBOX_IMAGE: "AGEWORK_SANDBOX_OPENSANDBOX_IMAGE",
  SANDBOX_OPENSANDBOX_TIMEOUT_SECONDS:
    "AGEWORK_SANDBOX_OPENSANDBOX_TIMEOUT_SECONDS",
  SANDBOX_OPENSANDBOX_USE_SERVER_PROXY:
    "AGEWORK_SANDBOX_OPENSANDBOX_USE_SERVER_PROXY",
  AGENT_EVENT_TRACE_ENABLED: "AGEWORK_AGENT_EVENT_TRACE_ENABLED",
  AGENT_EVENT_TRACE_MAX_FILE_MB: "AGEWORK_AGENT_EVENT_TRACE_MAX_FILE_MB",
} as const;

export type EnvKey = (typeof EnvKey)[keyof typeof EnvKey];
